@isTest
public class TestUpdateAccountIfOpp {
 @istest static void testUpdateAccount() {
        /*Account a = new Account(Name='testAccount', 
                                Industry='Other', 
                                Type='Prospect');
        insert a; 
        
        Product2 prod = new Product2(isactive=false, id='01t6F000009pKUQ');
        update prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
        
        Opportunity opp = new Opportunity(Name='Test', 
                                          Account = a, 
                                         
                                          NextStep='test',
                                          PriceBook2 = customPB,
                                         
                                          CloseDate = System.today(),
                                          AccountId=a.Id, 
                                          StageName='Closed Won - One Time', 
                                          Probability=100);
       
       insert opp; 
        
       System.assertEquals('Customer', a.Type);*/
    }
}